class Universiteler {
  static List<String> tumUniversiteler() {
    return [
      "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi",
      "Adıyaman Üniversitesi",
      "Afyon Kocatepe Üniversitesi",
      "Ağrı İbrahim Çeçen Üniversitesi",
      "Aksaray Üniversitesi",
      "Amasya Üniversitesi",
      "Anadolu Üniversitesi",
      "Ankara Hacı Bayram Veli Üniversitesi",
      "Ankara Müzik ve Güzel Sanatlar Üniversitesi",
      "Ankara Sosyal Bilimler Üniversitesi",
      "Ankara Üniversitesi",
      "Ankara Yıldırım Beyazıt Üniversitesi",
      "Ardahan Üniversitesi",
      "Artvin Çoruh Üniversitesi",
      "Atatürk Üniversitesi",
      "Balıkesir Üniversitesi",
      "Bandırma Onyedi Eylül Üniversitesi",
      "Bartın Üniversitesi",
      "Batman Üniversitesi",
      "Bayburt Üniversitesi",
      "Bilecik Şeyh Edebali Üniversitesi",
      "Bingöl Üniversitesi",
      "Bitlis Eren Üniversitesi",
      "Bolu Abant İzzet Baysal Üniversitesi",
      "Boğaziçi Üniversitesi",
      "Burdur Mehmet Akif Ersoy Üniversitesi",
      "Bursa Teknik Üniversitesi",
      "Bursa Uludağ Üniversitesi",
      "Çanakkale Onsekiz Mart Üniversitesi",
      "Çankırı Karatekin Üniversitesi",
      "Çukurova Üniversitesi",
      "Dicle Üniversitesi",
      "Dokuz Eylül Üniversitesi",
      "Düzce Üniversitesi",
      "Ege Üniversitesi",
      "Erciyes Üniversitesi",
      "Erzincan Binali Yıldırım Üniversitesi",
      "Erzurum Teknik Üniversitesi",
      "Eskişehir Osmangazi Üniversitesi",
      "Eskişehir Teknik Üniversitesi",
      "Fırat Üniversitesi",
      "Galatasaray Üniversitesi",
      "Gazi Üniversitesi",
      "Gaziantep Üniversitesi",
      "Gaziantep İslam Bilim ve Teknoloji Üniversitesi",
      "Gebze Teknik Üniversitesi",
      "Giresun Üniversitesi",
      "Gümüşhane Üniversitesi",
      "Hacettepe Üniversitesi",
      "Hakkari Üniversitesi",
      "Harran Üniversitesi",
      "Hatay Mustafa Kemal Üniversitesi",
      "Hitit Üniversitesi",
      "Iğdır Üniversitesi",
      "Isparta Uygulamalı Bilimler Üniversitesi",
      "İnönü Üniversitesi",
      "İskenderun Teknik Üniversitesi",
      "İstanbul Medeniyet Üniversitesi",
      "İstanbul Teknik Üniversitesi",
      "İstanbul Üniversitesi",
      "İstanbul Üniversitesi-Cerrahpaşa",
      "İzmir Bakırçay Üniversitesi",
      "İzmir Demokrasi Üniversitesi",
      "İzmir Kâtip Çelebi Üniversitesi",
      "İzmir Yüksek Teknoloji Enstitüsü",
      "Kafkas Üniversitesi",
      "Kahramanmaraş İstiklal Üniversitesi",
      "Kahramanmaraş Sütçü İmam Üniversitesi",
      "Karabük Üniversitesi",
      "Karadeniz Teknik Üniversitesi",
      "Karamanoğlu Mehmetbey Üniversitesi",
      "Kastamonu Üniversitesi",
      "Kayseri Üniversitesi",
      "Kırıkkale Üniversitesi",
      "Kırklareli Üniversitesi",
      "Kırşehir Ahi Evran Üniversitesi",
      "Kilis 7 Aralık Üniversitesi",
      "Kocaeli Üniversitesi",
      "Konya Teknik Üniversitesi",
      "Kütahya Dumlupınar Üniversitesi",
      "Kütahya Sağlık Bilimleri Üniversitesi",
      "Malatya Turgut Özal Üniversitesi",
      "Manisa Celâl Bayar Üniversitesi",
      "Mardin Artuklu Üniversitesi",
      "Marmara Üniversitesi",
      "Mersin Üniversitesi",
      "Mimar Sinan Güzel Sanatlar Üniversitesi",
      "Muğla Sıtkı Koçman Üniversitesi",
      "Munzur Üniversitesi",
      "Muş Alparslan Üniversitesi",
      "Necmettin Erbakan Üniversitesi",
      "Nevşehir Hacı Bektaş Veli Üniversitesi",
      "Niğde Ömer Halisdemir Üniversitesi",
      "Ondokuz Mayıs Üniversitesi",
      "Ordu Üniversitesi",
      "Orta Doğu Teknik Üniversitesi",
      "Osmaniye Korkut Ata Üniversitesi",
      "Pamukkale Üniversitesi",
      "Recep Tayyip Erdoğan Üniversitesi",
      "Sakarya Uygulamalı Bilimler Üniversitesi",
      "Sakarya Üniversitesi",
      "Samsun Üniversitesi",
      "Selçuk Üniversitesi",
      "Siirt Üniversitesi",
      "Sinop Üniversitesi",
      "Sivas Bilim ve Teknoloji Üniversitesi",
      "Sivas Cumhuriyet Üniversitesi",
      "Süleyman Demirel Üniversitesi",
      "Şırnak Üniversitesi",
      "Tarsus Üniversitesi",
      "Tekirdağ Namık Kemal Üniversitesi",
      "Tokat Gaziosmanpaşa Üniversitesi",
      "Trabzon Üniversitesi",
      "Trakya Üniversitesi",
      "Türk-Alman Üniversitesi",
      "Uşak Üniversitesi",
      "Van Yüzüncü Yıl Üniversitesi",
      "Yalova Üniversitesi",
      "Yıldız Teknik Üniversitesi",
      "Yozgat Bozok Üniversitesi",
      "Zonguldak Bülent Ecevit Üniversitesi",
      // Vakıf Üniversiteleri
      "Acıbadem Mehmet Ali Aydınlar Üniversitesi",
      "Altınbaş Üniversitesi",
      "Antalya Bilim Üniversitesi",
      "Atılım Üniversitesi",
      "Bahçeşehir Üniversitesi",
      "Başkent Üniversitesi",
      "Beykent Üniversitesi",
      "Beykoz Üniversitesi",
      "Bezmiâlem Vakıf Üniversitesi",
      "Biruni Üniversitesi",
      "Çağ Üniversitesi",
      "Çankaya Üniversitesi",
      "Doğuş Üniversitesi",
      "Fatih Sultan Mehmet Vakıf Üniversitesi",
      "Fenerbahçe Üniversitesi",
      "Haliç Üniversitesi",
      "Hasan Kalyoncu Üniversitesi",
      "Işık Üniversitesi",
      "İbn Haldun Üniversitesi",
      "İstanbul 29 Mayıs Üniversitesi",
      "İstanbul Arel Üniversitesi",
      "İstanbul Atlas Üniversitesi",
      "İstanbul Aydın Üniversitesi",
      "İstanbul Bilgi Üniversitesi",
      "İstanbul Esenyurt Üniversitesi",
      "İstanbul Galata Üniversitesi",
      "İstanbul Gedik Üniversitesi",
      "İstanbul Gelişim Üniversitesi",
      "İstanbul Kent Üniversitesi",
      "İstanbul Kültür Üniversitesi",
      "İstanbul Nişantaşı Üniversitesi",
      "İstanbul Okan Üniversitesi",
      "İstanbul Rumeli Üniversitesi",
      "İstanbul Sabahattin Zaim Üniversitesi",
      "İstanbul Ticaret Üniversitesi",
      "İstanbul Topkapı Üniversitesi",
      "İstinye Üniversitesi",
      "İzmir Ekonomi Üniversitesi",
      "Kadir Has Üniversitesi",
      "Koç Üniversitesi",
      "KTO Karatay Üniversitesi",
      "Lokman Hekim Üniversitesi",
      "Maltepe Üniversitesi",
      "MEF Üniversitesi",
      "Nuh Naci Yazgan Üniversitesi",
      "Özyeğin Üniversitesi",
      "Piri Reis Üniversitesi",
      "Sabancı Üniversitesi",
      "Sanko Üniversitesi",
      "TED Üniversitesi",
      "TOBB Ekonomi ve Teknoloji Üniversitesi",
      "Toros Üniversitesi",
      "Ufuk Üniversitesi",
      "Üsküdar Üniversitesi",
      "Yaşar Üniversitesi",
      "Yeditepe Üniversitesi",
    ];
  }

  /// Arama metnine göre filtrelenmiş üniversite listesi döndürür
  static List<String> ara(String query) {
    if (query.isEmpty) return tumUniversiteler();
    return tumUniversiteler()
        .where((uni) => uni.toLowerCase().contains(query.toLowerCase()))
        .toList();
  }
}